name: Ruby
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Checks
        run: |
          gem install awesome_bot
          awesome_bot --allow-redirect --request-delay 1 README.md
